= GitHub Repository Naming Suggestion Service

Let AI suggest namings for your GitHub repositories. Open any public repo on GitHub, and use the extension as a client to naming suggestion service API available on RapidAPI (API credentials need to be set up in the extension options).

***

Ever wondered how to name your GitHub repository?

Often we have a very good understanding of what our code does, but we don't know how to put all of that into a single repository name.

That's where _GHRNS_ (GitHub Repository Naming Suggestion Service) comes into play: It automatically suggests meaningful names for your repository based on your repository description.

Suggestions are generated by artificial intelligence from https://openai.com/[OpenAI].

The service is available as a REST API as well as the web browser extension, which makes use of the same API.

The browser extension automatically detects the current repository you are looking at on GitHub, then you can generate suggestions from the web browser extensions pop-up.

The extension requires credentials for the _GHRNS_ API. The API is distributed over RapidAPI. Once you https://rapidapi.com/devidw/api/github-repository-naming-service/[get your API key], you can set it up in the extension options and start generating suggestions.


== Privacy practices

=== Single purpose
Its purpose is to generate meaningful repository names for your GitHub repositories. It acs as a helper tool for developers to name their repositories faster and easier.


=== Permission justification

==== `storage` justification
Storage is needed to save the API credentials. The API host and the API key are stored.

==== `tabs` justification
Access to the browser tabs is needed to detect the current repository. See if the current tab is a GitHub repository, and if so, get the repository name as well as the username, to pass these details to the API, which then generates the suggestions.

// ==== `activeTab` justification


// ==== Host permission justification


==== Remote code justification
Remote code is needed to generate suggestions, since the corresponding API is not included in the extension itself, because it involks server-side code.
